version: '3.7'

services: 
    newapp:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports: 
            - 8000:8000
        env_file: 
            - ./django.env
        
    redis:
        image: redis
